---
## test a standalone installation
- name: Converge
  hosts: standaloneinst
  roles:
    - role: ansible-rabbitmq-minimalistic
  post_tasks:
    - name: Check RabbitMQ connectivity
      command: rabbitmq-diagnostics -q check_port_connectivity
      register: portconnstat
      changed_when: false
      failed_when: portconnstat.rc != 0
  vars:
    rabbitmq_conf_template: "molecule/default/tests/fixtures/rabbitmq.conf.j2"

## test a clustered installation
# create cluster
- name: Converge
  hosts: group1
  serial: 1
  roles:
    - role: ansible-rabbitmq-minimalistic
  vars:
    rabbitmq_conf_template: "molecule/default/tests/fixtures/rabbitmq.conf.cluster.j2"
    rabbitmq_erlang_cookie: "XXXXXXXXXXXXXXXXXXXX"
# check cluster
- name: Converge
  hosts: group1
  tasks:
    - name: Get RabbitMQ cluster status
      command: rabbitmqctl cluster_status
      register: clusterstatus
      changed_when: false
    - name: Check if cluster nodes were correctly joined
      fail:
        msg: "Seems like not all the nodes joined the cluster"
      when: ("debian-9-instance-1" not in clusterstatus.stdout) or
            ("debian-9-instance-2" not in clusterstatus.stdout) or
            ("debian-9-instance-3" not in clusterstatus.stdout)
